version: '1.0'

networks:
  spring-security:

services:
  keycloak-mysql:
    container_name: keycloak-mysql
    networks:
      - spring-security
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - 1001:3306

  keycloak:
    container_name: keycloak
    networks:
      - spring-security
    image: quay.io/keycloak/keycloak:22.0.5
    restart: always
    command: [ "start-dev" ]
    # command: [ "start-dev", "--import-realm"]
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak-mysql:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: g7fJpR$38l^vZq!FxYr2
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_PROXY: edge  

    ports:
      - "1000:8080"
    expose:
      - "1000"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql